### ISSUE TITLE
Grunt borks on remote URL in barceloneta.plone.local.less 

### ISSUE THREAD

**Issue by djowett** [plone/plonetheme.barceloneta#114] opened 2016-09-13 18:07 UTC
I'm just running Grunt on a local clone of barceloneta, and I get the error below when I change a file.

```
$ grunt
Running "watch" task
Waiting...
>> File "plonetheme/barceloneta/theme/less/sitenav.plone.less" changed.
Running "less:dist" (less) task
>> FileError: optional dependency 'request' required to import over http(s)
>>  in plonetheme/barceloneta/theme/less/barceloneta.plone.local.less on line 1, column 1:
>> 1 @import url("https://raw.githubusercontent.com/plone/Products.CMFPlone/master/Products/CMFPlone/static/patterns/toolbar/src/css/variables.less");
>> 2 @import "barceloneta.plone.less";
Warning: Error compiling plonetheme/barceloneta/theme/less/barceloneta.plone.local.less Use --force to continue.

Aborted due to warnings.
```

Obviously I can just install `npm install request` - but then that should be in the theme dependencies - or documented somewhere.  However I question why we have a remote URL in this `barceloneta.plone.local.less` file, though could the role of this file be documented?
All the other remote (github.com) references are already  removed from this repo - so maybe this one should be too?

**Comment by vincentfretin** [comment] 2020-07-08 08:43
duplicate of #174 this has long been fixed we now use a commit and not master in the url.
Btw I didn't know about grunt command in this package, I found out a command to compile the theme with `npx lessc` that has better url for the sourcemap (we could maybe fix the Gruntfile.js as well, I didn't look at it), I added it in the README of the 2.x branch https://github.com/plone/plonetheme.barceloneta/tree/2.x

**Closed** 2020-07-08 08:43 UTC
